name: Node.js CI
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version:
          - 20.x
    steps:
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install HTML driver
        run: npx appium driver install --source local "$(pwd)"
      - name: Run Appium server
        run: |
          npx appium server &
          while ! nc -z localhost 4723; do
            sleep 1
          done
      - name: Run tests
        run: xvfb-run -a -s "-screen 0 1680x1050x24" npm test
