name: Node.js CI
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm ci
      - name: Install Appium
        run: npm install -g appium@next
      - name: Install HTML driver
        run: appium driver install --source local "$(pwd)"
      - name: Run Appium server
        run: |
          appium server &
          while ! nc -z localhost 4723; do
            sleep 1
          done
      - name: Run tests
        run: xvfb-run -a -s "-screen 0 1680x1050x24" npm test
